module.exports = {
  TOKEN:                   process.env.TOKEN,
  CLIENT_ID:               process.env.CLIENT_ID,
  CLIENT_SECRET:           process.env.CLIENT_SECRET,
  PUBLIC_KEY:              process.env.PUBLIC_KEY,
  GUILD_ID:                process.env.GUILD_ID,
  PANEL_GUILD_ID:          process.env.PANEL_GUILD_ID || process.env.GUILD_ID,
  TICKET_PANEL_CHANNEL_ID: process.env.TICKET_PANEL_CHANNEL_ID,
  LOG_CHANNEL_ID:          process.env.LOG_CHANNEL_ID,
  STAFF_ROLE_ID:           process.env.STAFF_ROLE_ID,
  STAFF_ROLE_ID2:          process.env.STAFF_ROLE_ID2,
  STAFF_ROLE_ID3:          process.env.STAFF_ROLE_ID3,
  CATEGORIES: {
    GENERAL: process.env.CATEGORY_GENERAL,
    FACTION: process.env.CATEGORY_FACTION,
    SUPPORT: process.env.CATEGORY_SUPPORT,
  },
  WEB_BASE_URL: process.env.WEB_BASE_URL,
  TICKET_OPTIONS: [
    {
      label: '일반 문의',
      description: '일반적인 문의는 이 티켓을 이용해 주세요',
      value: 'GENERAL',
      emoji: '',
      categoryKey: 'GENERAL',
      channelPrefix: '일반문의',
    },
    {
      label: '팩션창설 문의',
      description: '팩션 창설 관련 문의는 이 티켓을 이용해 주세요',
      value: 'FACTION',
      emoji: '',
      categoryKey: 'FACTION',
      channelPrefix: '팩션창설문의',
    },
    {
      label: '후원 문의',
      description: '후원 상품 문의 및 개인 상품 신청은 이 티켓을 이용해 주세요',
      value: 'SUPPORT',
      emoji: '',
      categoryKey: 'SUPPORT',
      channelPrefix: '후원문의',
    },
  ],
};
